version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:1337
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    init: true
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress:1337
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    init: true
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx:1337
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    init: true
    restart: on-failure


networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mkatfi/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mkatfi/data/wordpress'
